name: Deploiement de Notre App FastAPI
on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_USER: ${{ vars.SERVER_USERNAME }}
  SERVER_HOST: ${{ vars.SERVER_IP}}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo

jobs:
  check-bats-version:
    runs-on: ["self-hosted"]
    steps:
      - name: Configure Actions/Workflow
        uses: actions/checkout@v4

      #- name: Install Docker app/tool
      #  become: True
      #  run: |
      #    dnf -y install docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF' 
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d --name fastapi-app -p 8000:80 ${{ env.IMAGE_NAME }}:latest
          EOF
