name: Deploiement de Notre App FastAPI
on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_USER: ${{ vars.SERVER_USERNAME }}
  SERVER_HOST: ${{ vars.SERVER_IP}}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo-2

jobs:
  check-bats-version:
    runs-on: ["self-hosted"]
    steps:
      - name: Configure Actions/Workflow
        uses: actions/checkout@v4

      - name: Imprime les valeurs
        run: |
          echo '${{ secrets.DOCKERHUB_USERNAME }}'
          echo '${{ secrets.DOCKERHUB_TOKEN }}'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:0.0.2.
          docker push ${{ env.IMAGE_NAME }}:0.0.2
